import React, { useState, useEffect } from 'react';
import ApiService from '../services/api';
import InputForm from '../components/InputForm';
import ComparisonTable from '../components/ComparisonTable';
import DetailedComparison from '../components/DetailedComparison';
import TradeoffExplanation from '../components/TradeoffExplanation';
import Recommendation from '../components/Recommendation';
import { NeonButton } from '../components/ui/NeonButton';

const Home = ({ currentView: externalView, setCurrentView: setExternalView }) => {
  const [view, setView] = useState(externalView || 'categories');
  const [categories, setCategories] = useState([]);
  const [selectedCategory, setSelectedCategory] = useState(null);
  const [comparisonResult, setComparisonResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  // Sync with external view changes
  React.useEffect(() => {
    if (externalView && externalView !== view) {
      setView(externalView);
      // Reset state when going back to categories
      if (externalView === 'categories') {
        setSelectedCategory(null);
        setComparisonResult(null);
        setError(null);
      }
    }
  }, [externalView, view]);

  // Update external view when internal view changes
  const updateView = (newView) => {
    setView(newView);
    if (setExternalView) {
      setExternalView(newView);
    }
  };

  useEffect(() => {
    loadCategories();
  }, []);

  const loadCategories = async () => {
    try {
      setLoading(true);
      const data = await ApiService.getCategories();
      setCategories(data);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleCategorySelect = async (categoryId) => {
    try {
      setLoading(true);
      const categoryData = await ApiService.getCategoryOptions(categoryId);
      setSelectedCategory(categoryData);
      updateView('form');
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleComparisonSubmit = async (formData) => {
    try {
      setLoading(true);
      const result = await ApiService.createComparison({
        category: selectedCategory.id,
        ...formData
      });
      setComparisonResult(result);
      updateView('results');
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleBackToCategories = () => {
    updateView('categories');
    setSelectedCategory(null);
    setComparisonResult(null);
    setError(null);
  };

  const handleNewComparison = () => {
    updateView('form');
    setComparisonResult(null);
    setError(null);
  };

  const handleDownloadResults = () => {
    if (!comparisonResult) return;
    
    // Get sorted options by score
    const sortedOptions = comparisonResult.result.options
      .map(opt => ({
        name: typeof opt === 'string' ? opt : opt.name,
        data: typeof opt === 'string' ? null : opt,
        score: comparisonResult.result.scores[typeof opt === 'string' ? opt : opt.name] || 0
      }))
      .sort((a, b) => b.score - a.score);
    
    // Build comprehensive text report
    let resultsText = '';
    
    // Header
    resultsText += '═══════════════════════════════════════════════════════════════\n';
    resultsText += '                 REFEREEAI COMPARISON RESULTS                  \n';
    resultsText += '═══════════════════════════════════════════════════════════════\n\n';
    
    resultsText += `Category: ${comparisonResult.title}\n`;
    resultsText += `Date: ${new Date().toLocaleString()}\n`;
    resultsText += `Generated by: RefereeAI - Decision Clarity Platform\n\n`;
    
    // Scores Section
    resultsText += '═══════════════════════════════════════════════════════════════\n';
    resultsText += '                         SCORE SUMMARY                         \n';
    resultsText += '═══════════════════════════════════════════════════════════════\n\n';
    
    sortedOptions.forEach((opt, idx) => {
      const rank = idx + 1;
      const stars = '★'.repeat(Math.round(opt.score));
      resultsText += `${rank}. ${opt.name}\n`;
      resultsText += `   Score: ${opt.score.toFixed(1)}/5.0 ${stars}\n`;
      if (idx === 0) {
        resultsText += `   ⭐ Strong fit for your constraints\n`;
      }
      resultsText += `\n`;
    });
    
    // Detailed Analysis Section
    resultsText += '\n═══════════════════════════════════════════════════════════════\n';
    resultsText += '                    DETAILED OPTION ANALYSIS                   \n';
    resultsText += '═══════════════════════════════════════════════════════════════\n\n';
    
    sortedOptions.forEach((opt, idx) => {
      if (!opt.data) return;
      
      resultsText += `\n${'─'.repeat(63)}\n`;
      resultsText += `${idx + 1}. ${opt.name.toUpperCase()} (Score: ${opt.score.toFixed(1)}/5.0)\n`;
      resultsText += `${'─'.repeat(63)}\n\n`;
      
      // Description
      if (opt.data.description) {
        resultsText += `Description:\n`;
        resultsText += `${opt.data.description}\n\n`;
      }
      
      // Strengths
      resultsText += `✓ STRENGTHS:\n`;
      resultsText += `${'─'.repeat(63)}\n`;
      if (opt.data.strengths && opt.data.strengths.length > 0) {
        opt.data.strengths.forEach((strength, i) => {
          resultsText += `  ${i + 1}. ${strength}\n`;
        });
      } else {
        resultsText += `  No specific strengths listed.\n`;
      }
      resultsText += `\n`;
      
      // Weaknesses/Considerations
      resultsText += `⚠ CONSIDERATIONS:\n`;
      resultsText += `${'─'.repeat(63)}\n`;
      if (opt.data.weaknesses && opt.data.weaknesses.length > 0) {
        opt.data.weaknesses.forEach((weakness, i) => {
          resultsText += `  ${i + 1}. ${weakness}\n`;
        });
      } else {
        resultsText += `  No specific considerations listed.\n`;
      }
      resultsText += `\n`;
      
      // Best For
      resultsText += `🎯 BEST SUITED FOR:\n`;
      resultsText += `${'─'.repeat(63)}\n`;
      if (opt.data.bestFor && opt.data.bestFor.length > 0) {
        opt.data.bestFor.forEach((use, i) => {
          resultsText += `  → ${use}\n`;
        });
      } else {
        resultsText += `  No specific use cases listed.\n`;
      }
      resultsText += `\n`;
    });
    
    // Recommendation Section
    resultsText += '\n═══════════════════════════════════════════════════════════════\n';
    resultsText += '                        RECOMMENDATION                         \n';
    resultsText += '═══════════════════════════════════════════════════════════════\n\n';
    resultsText += `${comparisonResult.result.recommendation}\n\n`;
    
    // Trade-offs Section
    resultsText += '\n═══════════════════════════════════════════════════════════════\n';
    resultsText += '                  TRADE-OFFS & CONSIDERATIONS                  \n';
    resultsText += '═══════════════════════════════════════════════════════════════\n\n';
    
    if (comparisonResult.result.tradeoffs && comparisonResult.result.tradeoffs.length > 0) {
      comparisonResult.result.tradeoffs.forEach((tradeoff, idx) => {
        resultsText += `${idx + 1}. ${tradeoff}\n\n`;
      });
    } else {
      resultsText += `No significant trade-offs detected.\n\n`;
    }
    
    // Footer
    resultsText += '\n═══════════════════════════════════════════════════════════════\n';
    resultsText += '                         END OF REPORT                         \n';
    resultsText += '═══════════════════════════════════════════════════════════════\n\n';
    resultsText += `This report was generated by RefereeAI to help you make an\n`;
    resultsText += `informed decision. Remember: there is no single "best" option,\n`;
    resultsText += `only the option that best fits YOUR specific needs.\n\n`;
    resultsText += `For more comparisons, visit: http://localhost:3000\n`;
    
    // Create and download the text file
    const blob = new Blob([resultsText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `refereeai-comparison-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (loading && view === 'categories') {
    return React.createElement('div', {
      className: 'flex items-center justify-center min-h-screen'
    }, React.createElement('div', {
      className: 'text-center'
    }, [
      React.createElement('div', {
        key: 'spinner',
        className: 'w-16 h-16 border-4 border-gray-700 border-t-indigo-500 rounded-full animate-spin mx-auto mb-4'
      }),
      React.createElement('p', {
        key: 'text',
        className: 'text-sm text-gray-400'
      }, 'Loading categories...')
    ]));
  }

  return React.createElement('div', {
    className: 'animate-fade-in w-full'
  }, [
    // Categories View - Hero + Grid
    view === 'categories' && React.createElement('div', {
      key: 'categories',
      className: 'w-full'
    }, [
      // Hero Section - Centered
      React.createElement('section', {
        key: 'hero',
        className: 'w-full flex items-center justify-center px-6 pt-32 pb-20'
      }, React.createElement('div', {
        className: 'max-w-4xl mx-auto text-center'
      }, [
        React.createElement('h1', {
          key: 'title',
          className: 'text-6xl md:text-8xl font-bold mb-6 tracking-tight bg-gradient-to-b from-white via-white to-gray-500 bg-clip-text text-transparent'
        }, 'Make Informed Decisions'),
        React.createElement('p', {
          key: 'subtitle',
          className: 'text-xl md:text-2xl text-gray-400 max-w-2xl mx-auto leading-relaxed'
        }, 'Compare technical options with clarity. Understand trade-offs. Choose with confidence.')
      ])),

      // Categories Grid - Centered
      React.createElement('section', {
        key: 'categories-section',
        id: 'categories',
        className: 'w-full flex items-center justify-center px-6 pb-16'
      }, React.createElement('div', {
        className: 'max-w-6xl mx-auto w-full'
      }, [
        React.createElement('h2', {
          key: 'heading',
          className: 'text-3xl font-bold text-white mb-10 text-center'
        }, 'Select a Category'),
        React.createElement('div', {
          key: 'grid',
          className: 'grid md:grid-cols-2 lg:grid-cols-3 gap-6'
        }, categories.map(cat =>
          React.createElement('button', {
            key: cat.id,
            onClick: () => handleCategorySelect(cat.id),
            className: 'group relative bg-gradient-to-br from-gray-900/90 to-gray-800/90 backdrop-blur-xl border border-white/10 rounded-2xl p-8 text-left transition-all duration-300 hover:border-indigo-500/50 hover:shadow-2xl hover:shadow-indigo-500/20 hover:-translate-y-2'
          }, [
            React.createElement('div', {
              key: 'icon',
              className: 'text-5xl mb-4 transform group-hover:scale-110 transition-transform duration-300'
            }, cat.icon),
            React.createElement('h3', {
              key: 'title',
              className: 'text-xl font-bold text-white mb-2 group-hover:text-indigo-400 transition-colors'
            }, cat.category),
            React.createElement('p', {
              key: 'count',
              className: 'text-sm text-gray-400 mb-4'
            }, `${cat.optionCount} options available`),
            React.createElement('div', {
              key: 'action',
              className: 'flex items-center text-sm font-medium text-indigo-400 group-hover:text-indigo-300'
            }, [
              React.createElement('span', { key: 'text' }, 'Compare'),
              React.createElement('span', { 
                key: 'arrow',
                className: 'ml-2 transition-transform group-hover:translate-x-2'
              }, '→')
            ])
          ])
        ))
      ])),

      // How It Works Section - Centered
      React.createElement('section', {
        key: 'how-it-works',
        id: 'how-it-works',
        className: 'w-full flex items-center justify-center px-6 py-20'
      }, React.createElement('div', {
        className: 'max-w-5xl mx-auto w-full'
      }, [
        React.createElement('h2', {
          key: 'title',
          className: 'text-3xl font-bold text-white mb-12 text-center'
        }, 'How It Works'),
        React.createElement('div', {
          key: 'steps',
          className: 'grid md:grid-cols-3 gap-10'
        }, [
          React.createElement('div', {
            key: 'step1',
            className: 'text-center'
          }, [
            React.createElement('div', {
              key: 'number',
              className: 'w-16 h-16 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-full flex items-center justify-center mx-auto mb-6 shadow-lg shadow-indigo-500/50'
            }, React.createElement('span', {
              className: 'text-2xl font-bold text-white'
            }, '1')),
            React.createElement('h3', {
              key: 'title',
              className: 'text-xl font-bold text-white mb-3'
            }, 'Select a Category'),
            React.createElement('p', {
              key: 'desc',
              className: 'text-base text-gray-400 leading-relaxed'
            }, 'Choose from programming languages, frameworks, databases, cloud providers, and more.')
          ]),
          React.createElement('div', {
            key: 'step2',
            className: 'text-center'
          }, [
            React.createElement('div', {
              key: 'number',
              className: 'w-16 h-16 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-full flex items-center justify-center mx-auto mb-6 shadow-lg shadow-indigo-500/50'
            }, React.createElement('span', {
              className: 'text-2xl font-bold text-white'
            }, '2')),
            React.createElement('h3', {
              key: 'title',
              className: 'text-xl font-bold text-white mb-3'
            }, 'Define Your Constraints'),
            React.createElement('p', {
              key: 'desc',
              className: 'text-base text-gray-400 leading-relaxed'
            }, 'Tell us about your budget, scale, team expertise, and timeline to get personalized insights.')
          ]),
          React.createElement('div', {
            key: 'step3',
            className: 'text-center'
          }, [
            React.createElement('div', {
              key: 'number',
              className: 'w-16 h-16 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-full flex items-center justify-center mx-auto mb-6 shadow-lg shadow-indigo-500/50'
            }, React.createElement('span', {
              className: 'text-2xl font-bold text-white'
            }, '3')),
            React.createElement('h3', {
              key: 'title',
              className: 'text-xl font-bold text-white mb-3'
            }, 'Get Clear Analysis'),
            React.createElement('p', {
              key: 'desc',
              className: 'text-base text-gray-400 leading-relaxed'
            }, 'Receive detailed comparisons, understand trade-offs, and make confident decisions based on your needs.')
          ])
        ])
      ]))
    ]),

    // Form View - Centered
    view === 'form' && selectedCategory && React.createElement(InputForm, {
      key: 'form',
      category: selectedCategory,
      options: selectedCategory.options,
      onSubmit: handleComparisonSubmit,
      onBack: handleBackToCategories
    }),

    // Results View - Centered
    view === 'results' && comparisonResult && React.createElement('div', {
      key: 'results',
      className: 'w-full flex items-center justify-center px-6 py-20 animate-slide-up'
    }, React.createElement('div', {
      className: 'max-w-6xl mx-auto w-full'
    }, [
      // Result Header - Centered
      React.createElement('div', {
        key: 'header',
        className: 'mb-16 text-center'
      }, [
        React.createElement('div', {
          key: 'icon',
          className: 'w-20 h-20 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-2xl flex items-center justify-center mx-auto mb-6 shadow-lg shadow-indigo-500/50'
        }, React.createElement('span', {
          className: 'text-4xl'
        }, '📊')),
        React.createElement('h2', {
          key: 'title',
          className: 'text-4xl md:text-5xl font-bold text-white mb-4'
        }, 'Comparison Results'),
        React.createElement('p', {
          key: 'subtitle',
          className: 'text-xl text-gray-400'
        }, comparisonResult.title)
      ]),

      // Score Summary
      React.createElement(ComparisonTable, {
        key: 'table',
        options: comparisonResult.result.options,
        scores: comparisonResult.result.scores
      }),

      React.createElement('div', {
        key: 'spacer1',
        className: 'h-16'
      }),

      // Detailed Comparison - Pros/Cons for Each Option
      React.createElement(DetailedComparison, {
        key: 'detailed',
        options: comparisonResult.result.options,
        scores: comparisonResult.result.scores
      }),

      React.createElement('div', {
        key: 'spacer2',
        className: 'h-16'
      }),

      // Recommendation - How Comparison Was Done
      React.createElement(Recommendation, {
        key: 'recommendation',
        recommendation: comparisonResult.result.recommendation,
        reasoning: comparisonResult.result.reasoning
      }),

      React.createElement('div', {
        key: 'spacer3',
        className: 'h-16'
      }),

      // Trade-offs
      React.createElement(TradeoffExplanation, {
        key: 'tradeoffs',
        tradeOffs: comparisonResult.result.tradeoffs
      }),

      // Actions with Download Button - All Equally Prominent
      React.createElement('div', {
        key: 'actions',
        className: 'flex flex-col sm:flex-row justify-center items-center gap-6 mt-20 mb-20'
      }, [
        React.createElement(NeonButton, {
          key: 'download',
          onClick: handleDownloadResults,
          variant: 'solid',
          size: 'lg',
          className: 'w-full sm:w-auto min-w-[220px] px-8'
        }, '📄 Download Report'),
        React.createElement(NeonButton, {
          key: 'new',
          onClick: handleNewComparison,
          variant: 'solid',
          size: 'lg',
          className: 'w-full sm:w-auto min-w-[220px] px-8'
        }, '🔄 New Comparison'),
        React.createElement(NeonButton, {
          key: 'back',
          onClick: handleBackToCategories,
          variant: 'solid',
          size: 'lg',
          className: 'w-full sm:w-auto min-w-[220px] px-8'
        }, '🏠 Browse Categories')
      ])
    ])),

    // Loading Overlay
    loading && view !== 'categories' && React.createElement('div', {
      key: 'loading',
      className: 'fixed inset-0 bg-black/80 backdrop-blur-sm flex items-center justify-center z-50'
    }, React.createElement('div', {
      className: 'bg-gray-900/95 border border-indigo-500/30 rounded-2xl p-10 shadow-2xl shadow-indigo-500/20 text-center'
    }, [
      React.createElement('div', {
        key: 'spinner',
        className: 'w-16 h-16 border-4 border-gray-700 border-t-indigo-500 rounded-full animate-spin mx-auto mb-6'
      }),
      React.createElement('p', {
        key: 'text',
        className: 'text-lg text-gray-300'
      }, 'Analyzing options...')
    ])),

    // Error Display
    error && React.createElement('div', {
      key: 'error',
      className: 'fixed bottom-8 right-8 bg-red-900/95 border border-red-500/50 rounded-xl p-6 shadow-2xl shadow-red-500/20 max-w-md animate-slide-up z-50'
    }, [
      React.createElement('p', {
        key: 'text',
        className: 'text-base text-red-200 mb-3'
      }, error),
      React.createElement('button', {
        key: 'close',
        onClick: () => setError(null),
        className: 'text-sm text-red-300 hover:text-red-100 font-medium transition-colors'
      }, 'Dismiss')
    ])
  ]);
};

export default Home;
